### ISSUE TITLE
cannot read databricks_group from azure devops

### ISSUE THREAD

**Issue by jasonhue8183** [databricks/terraform-databricks-examples#102]
<img width="1657" alt="image" src="https://github.com/databricks/terraform-databricks-examples/assets/8756745/c14dde31-451c-4e4a-b73d-0df05719c10a">

Error when issue command from azure devops " cannot read group: default auth: azure-cli: cannot get access token: ERROR: Please run 'az login' to setup account."
No issue if issue command from local. Appreciate for any advice!
<img width="557" alt="image" src="https://github.com/databricks/terraform-databricks-examples/assets/8756745/f513905c-0719-43ed-a41e-5426e65c677c">

**Comment by alexott** [comment]
You don't have authentication configured correctly (see [docs](https://registry.terraform.io/providers/databricks/databricks/latest/docs#special-configurations-for-azure) for supported methods). In general `azure-cli` doesn't work well from Azure DevOps, except in the case when you sign a service principal.

You can ask questions at [Databricks Community](https://community.databricks.com/) site - this specific not a provider issue or feature request.
