### ISSUE TITLE
Terraform aws provider version constraint conflict

### ISSUE THREAD

**Issue by trevorvoncannon** [databricks/terraform-databricks-examples#134]
When attempting to init the aws-exfiltration-protection module, it fails with:
``` terraform
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints ~> 5.20.1, >= 5.30.0
```

The listed constraints conflict with one another as ~>5.20.1 allows all aws 5.20.x versions (restricting the right-most value), but the other constraint requires that the version be greater than or equal to 5.30.0.

This should be adjusted to ~>5.20 at least or moved to >5.30.0 to conform to the child module.

https://github.com/databricks/terraform-databricks-examples/blob/adb-exfiltration-protection-update/modules/aws-exfiltration-protection/versions.tf#L11

**Comment by alexott** [comment]
fixed by #135
