### ISSUE TITLE
DBFS with private link does not work 

### ISSUE THREAD

**Issue by csimplestring** [databricks/terraform-databricks-examples#40]
Hi, I am using the adb-with-private-links-exfiltration-protection module, in the example it said:
```
firewallfqdn = [                                                      // we don't need scc relay and dbfs fqdn since they will go to private endpoint
  "dbartifactsprodseap.blob.core.windows.net",                        //databricks artifacts
  "dbartifactsprodeap.blob.core.windows.net",                         //databricks artifacts secondary
  "dblogprodseasia.blob.core.windows.net",                            //log blob
  "prod-southeastasia-observabilityeventhubs.servicebus.windows.net", //eventhub
  "cdnjs.com",                                                        //ganglia
]
```
"we don't need scc relay and dbfs fqdn since they will go to private endpoint, however, the dbfs is still not accessible when creating cluster. I have to manually add the DBFS fqdn in firewall, then it works. 

Is it intended behaviour ?

**Comment by hwang-db** [comment]
DBFS PE is already defined in: https://github.com/databricks/terraform-databricks-examples/blob/main/modules/adb-with-private-links-exfiltration-protection/privateendpoint.tf#L53

**Comment by csimplestring** [comment]
@hwang-db we do use that block in our terraform. The issue is we can not create cluster. Unless I add the dbfs fqdn in the firewall.  So I am wondering if there is something missing in the source code? maybe I am wrong.

**Comment by csimplestring** [comment]
Hi @hwang-db  after checking a bit,  this module creates the storage account for dbfs, but it is accessible to the public internet even the private endpoint is created. 

A useful link https://stackoverflow.com/questions/68943377/is-it-possible-to-connect-to-azure-storage-account-with-private-ednpoint-from-da, i believe some vnet settings should also be done in this module. 

Please verify this and correct me if i am wrong.

**Comment by csimplestring** [comment]
but then this comment 
`
// we don't need scc relay and dbfs fqdn since they will go to private endpoint
` is misleading, right? Because I still have to add the dbfs fqdn in firewall, otherwise it fails to create cluster.
