### ISSUE TITLE
In GCP the "public_access_enabled" cannot be set to false when creating private access settings resource

### ISSUE THREAD

**Issue by ashkan-db** [databricks/terraform-databricks-examples#65]
On GCP, When creating [private access settings](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_private_access_settings) resource with TF, the "public_access_enabled" is set to the default value of "true" even if the argument is set to "false" in TF code.

**Comment by mgyucht** [comment]
This is addressed by https://github.com/databricks/terraform-provider-databricks/pull/3132. Thanks for raising!
