### ISSUE TITLE
 cannot create sql table: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by jasonhue8183** [databricks/terraform-databricks-examples#77]
![image](https://github.com/databricks/terraform-databricks-examples/assets/8756745/5d58c798-d333-4c39-9493-a22b5b7169f0)

![image](https://github.com/databricks/terraform-databricks-examples/assets/8756745/7cc1bc6f-f0bf-47c2-92c8-5c8f4b955e85)

Any idea for this issue?

**Comment by alexott** [comment]
Enable logs as per troubleshooting guide, and see. Most probably it's incorrect authentication. But this is not an issue with terraform examples, so closing it.

**Comment by alexott** [comment]
open issue in the provider, not in examples
