### ISSUE TITLE
ADB PrivateLink connectivity between data plane and DBFS requires blob private endpoint

### ISSUE THREAD

**Issue by jaikarve** [databricks/terraform-databricks-examples#86]
For the examples that attempt to create a private link between the data plane and DBFS, a blob private endpoint is required in addition to the DFS private endpoint that already exists in the adb-with-private-links-exfiltration-protection module.

**Comment by hwang-db** [comment]
Thanks! Yes both dfs and blob PE are required now for private connection from data plane to dbfs. We will update the examples asap.
